const path = require('path');

const INPUT_DIR = path.join(__dirname + '/input/');
const OUTPUT_DIR = path.join(__dirname + '/output/');

const CARDINAL_POINTS = {
  NORTE: 'NORTE',
  SUR: 'SUR',
  ORIENTE: 'ORIENTE',
  OCCIDENTE: 'OCCIDENTE'
};

const INITIAL_VALUES = {
  direction: CARDINAL_POINTS.NORTE,
  coordinates: { x: 0, y: 0 }
};

const DIRECTORIES_NOT_FOUND = {
  INPUT: 'INPUT_DIRECTORY_NOT_FOUND',
  OUTPUT: 'OUTPUT_DIRECTORY_NOT_FOUND'
};

const TURN_RIGTH_RULES = {
  NORTE: CARDINAL_POINTS.OCCIDENTE,
  SUR: CARDINAL_POINTS.ORIENTE,
  ORIENTE: CARDINAL_POINTS.NORTE,
  OCCIDENTE: CARDINAL_POINTS.SUR
};

const TURN_LEFT_RULES = {
  NORTE: CARDINAL_POINTS.ORIENTE,
  SUR: CARDINAL_POINTS.OCCIDENTE,
  ORIENTE: CARDINAL_POINTS.SUR,
  OCCIDENTE: CARDINAL_POINTS.NORTE
};

const INSTRUCTIONS = {
  MOVE: 'A',
  TURN_LEFT: 'I',
  TURN_RIGTH: 'D'
};

module.exports = {
  INPUT_DIR,
  OUTPUT_DIR,
  INITIAL_VALUES,
  DIRECTORIES_NOT_FOUND,
  TURN_RIGTH_RULES,
  TURN_LEFT_RULES,
  INSTRUCTIONS,
  CARDINAL_POINTS
};
